name: Feature Request
description: Suggest a new feature for Cursor Cloud Sync
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in improving Cursor Cloud Sync! Please describe your feature request below.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight Checklist
      description: Please confirm the following before submitting your feature request.
      options:
        - label: I have searched existing issues to make sure this feature hasn't already been requested
          required: true
        - label: I have read the documentation to make sure this feature doesn't already exist
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe what problem this would solve.
      placeholder: I'm frustrated when... / I need to... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: I would like... / The feature should... / This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I tried... / Another approach could be... / Currently I work around this by...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Essential for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Implementation Complexity (if known)
      description: If you have development experience, how complex do you think this would be?
      options:
        - I don't know
        - Simple - Small change or addition
        - Medium - Requires some refactoring
        - Complex - Major feature requiring significant changes

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature and how it would benefit you or other users
      placeholder: I would use this feature when... / This would help users who... / The benefit would be...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, examples, or references that would help explain this feature
      placeholder: Add any additional context, screenshots, or examples here...